/* src/Common/config_ipopt.h.  Generated by configure.  */
/* src/Common/config_ipopt.h.in. */

#ifndef __CONFIG_IPOPT_H__
#define __CONFIG_IPOPT_H__

/* Version number of project */
#define IPOPT_VERSION "3.10.1"

/* Major Version number of project */
#define IPOPT_VERSION_MAJOR 3

/* Minor Version number of project */
#define IPOPT_VERSION_MINOR 10

/* Release Version number of project */
#define IPOPT_VERSION_RELEASE 1

/* Define to the C type corresponding to Fortran INTEGER */
#define FORTRAN_INTEGER_TYPE int

#endif
