[build-system]
requires = [
    "Cython",
    "numpy>=1.13",
    "scipy",
    "setuptools",
    "wheel",
]
# Use the legacy backend because the local `versioneer.py` dependency that prevents isolated builds
build-backend = "setuptools.build_meta:__legacy__"
