package:
  name: pycalphad
  # If we're past a tag, build a dev version for CI purposes
  {% if environ.get('GIT_DESCRIBE_NUMBER', 0)|int != 0 %}
  version: {{ environ['GIT_DESCRIBE_TAG'] }}+{{ environ['GIT_DESCRIBE_NUMBER'] }}.g{{ environ['GIT_FULL_HASH'][:7] }}
  {% else %}
  # We're on a tag: render the version as-is
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}
  {% endif %}

source:
  {% if not environ.get('BINSTAR_PLATFORM', None) %}
  git_url: ../
  {% else %}
  # we're building on binstar, we already have the repo; treat as local path
  path: ../
  {% endif %}

requirements:
  build:
    - python
    - libpython # [win]
    - setuptools
    - matplotlib
    - pandas
    - nose
    - mock
    - xarray !=0.8
    - sympy >=1.2
    - pyparsing
    - tinydb
    - scipy
    - dask >=0.15
    - distributed
    - numpy >=1.9
    - dill
    - cython >=0.24
    - cyipopt
    - m2w64-toolchain # [win]

  run:
    - python
    - libpython # [win]
    - gcc # [osx or linux]
    - matplotlib
    - pandas
    - xarray !=0.8
    - sympy >=1.2
    - pyparsing
    - tinydb
    - scipy
    - dask >=0.15
    - distributed
    - numpy >=1.9
    - cython >=0.24
    - dill
    - cyipopt
    - m2w64-toolchain # [win]

build:
  script: python setup.py build_ext --compiler=mingw32 && python setup.py install --single-version-externally-managed --record=record.txt

test:
  # Python imports
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot

about:
  home: https://pycalphad.org/
  license: MIT
  summary: 'CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.'
