package:
  name: pycalphad
  # If we're past a tag, build a dev version for CI purposes
  {% if environ.get('GIT_DESCRIBE_NUMBER', 0)|int != 0 %}
  version: {{ environ['GIT_DESCRIBE_TAG'] }}+{{ environ['GIT_DESCRIBE_NUMBER'] }}.g{{ environ['GIT_FULL_HASH'][:7] }}
  {% else %}
  # We're on a tag: render the version as-is
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}
  {% endif %}

source:
  {% if not environ.get('BINSTAR_PLATFORM', None) %}
  git_url: ../
  {% else %}
  # we're building on binstar, we already have the repo; treat as local path
  path: ../
  {% endif %}

build:
  number: 0
  skip: true        # [win and not py>=35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - matplotlib
    - pandas
    - pytest
    - xarray >=0.11.2
    - sympy ==1.5
    - pyparsing
    - tinydb >=3.8
    - scipy
    - numpy >=1.13
    - cython >=0.24
    - cyipopt
    - python-symengine ==0.5.1
    - symengine ==0.5.0

  run:
    - python
    - matplotlib
    - pandas
    - xarray >=0.11.2
    - sympy ==1.5
    - pyparsing
    - tinydb >=3.8
    - scipy
    - numpy >=1.13
    - cython >=0.24
    - cyipopt
    - python-symengine ==0.5.1
    - symengine ==0.5.0

build:
  script: python setup.py build_ext && python setup.py install --single-version-externally-managed --record=record.txt

test:
  # Python imports
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot

about:
  home: https://pycalphad.org/
  license: MIT
  summary: 'CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.'
